libraryproject/libraryapp/urls.py
from django.urls import include, path
from .views import *

app_name = "libraryapp"

urlpatterns = [
    path('', home, name='home'),
    path('books/', book_list, name='books'),
    path('book/form', book_form, name='book_form'),
    path('books/<int:book_id>/', book_details, name='book'),
    path('library/form', library_form, name='library_form'),
    path('libraries/', library_list, name='libraries'),
    path('libraries/<int:library_id>/', library_details, name='library'),
    path('librarians/', list_librarians, name='librarians'),
    path('librarians/<int:librarian_id>/', librarian_details, name='librarian'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),

]

libraryproject/libraryproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path
from libraryapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libraryapp.urls')),
]

libraryproject/libraryapp/models/book.py
from django.db import models
from .library import Library
from .librarian import Librarian
from django.urls import reverse

class Book (models.Model):

    title = models.CharField(max_length=50)
    isbn = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    year_published = models.IntegerField()
    publisher = models.CharField(max_length=50)
    location = models.ForeignKey(Library, on_delete=models.CASCADE)
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)

    class Meta: 
        verbose_name = ("book")
        verbose_name_plural = ("books")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})
    

libraryproject/libraryapp/models/librarian.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .library import Library


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

libraryproject/libraryapp/models/library.py
from django.db import models
from django.urls import reverse

class Library (models.Model):

    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("library")
        verbose_name_plural = ("libraries")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("library _detail", kwargs={"pk": self.pk})

libraryproject/libraryapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

libraryproject/libraryapp/views.py
from django.shortcuts import render

# Create your views here.

libraryproject/libraryapp/views/connection.py
class Connection:
    db_path = "/home/chase/backend/workspace/python/library-management/libraryproject/db.sqlite3"

libraryproject/libraryapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

libraryproject/libraryapp/templates/books/detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ book.title }}</h1>
    <h2>By {{ book.author }}</h2>

    <div>Published in {{ book.year_published }}</div>
    <div>ISBN: {{ book.isbn }}</div>
  </body>
</html>

libraryproject/libraryapp/templates/books/form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Inventory Book</h1>


    <form action="{% url 'libraryapp:books' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="author">Author: </label>
          <input id="author" type="text" name="author">
      </fieldset>
      <fieldset>
          <label for="year_published">Year of publication: </label>
          <input id="year_published" type="number" name="year_published">
      </fieldset>
      <fieldset>
          <label for="isbn">ISBN: </label>
          <input id="isbn" type="text" name="isbn">
      </fieldset>
            <fieldset>
          <label for="publisher">Publisher: </label>
          <input id="publisher" type="text" name="publisher">
      </fieldset>
      <fieldset>
          <label for="location">Library: </label>
          <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                    <option value="{{ library.id }}">{{ library.name }}</option>
                {% endfor %}
          </select>
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

libraryproject/libraryapp/templates/books/list.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Books</h1>

    <ol>
    {% for book in all_books %}
        <li>
            <a href="{% url 'libraryapp:book' book.id %}"> {{ book.title }} </a>
            by {{book.author}} published in {{book.year_published}}
        </li>
    {% endfor %}
    </ol>
  </body>
</html>

libraryproject/libraryapp/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Nashville Library Management System</title>
</head>

<body>

    <h1>Welcome to the Nashville Library Management System</h1>

</body>

</html>

libraryproject/libraryapp/templates/librarians/detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Librarians</title>
  </head>
  <body>
    <h1>{{ librarian.first_name }} {{librarian.last_name}}</h1>
    <h2>{{ librarian.location_id  }}</h2>
    <div><i>{{ librarian.email }}</i></div>
  </body>
</html>

libraryproject/libraryapp/templates/librarians/list.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}
        <li>
            <a href="{% url 'libraryapp:librarian' librarian.id %}">{{ librarian.first_name }} {{ librarian.last_name }}</a>
        </li>
    {% endfor %}
    </ol>
  </body>
</html>

libraryproject/libraryapp/templates/libraries/detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ library.name }}</h1>
    <h2>Location: {{ library.address }}</h2>
  </body>
</html>

libraryproject/libraryapp/templates/libraries/form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Add Library</h1>


    <form action="{% url 'libraryapp:libraries' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="name">Name: </label>
          <input id="name" type="text" name="name">
      </fieldset>
      <fieldset>
          <label for="address">Address: </label>
          <input id="address" type="text" name="address">
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

libraryproject/libraryapp/templates/libraries/list.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Libraries</h1>

    <ol>
    {% for library in libraries %}
        <li>
            <a href="{% url 'libraryapp:library' library.id %}">{{library.name}}</a>{{library.address}}
        </li>
    {% endfor %}
    </ol>
  </body>
</html>